name: Generate DNS Blocklist

on:
  schedule:
    - cron: '0 0 * * *'  # Run daily at midnight UTC
  workflow_dispatch:  # Allow manual triggering

jobs:
  generate-blocklist:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Download Hagezi lists
        run: |
          curl -fsSL -o multi-normal.txt "https://raw.githubusercontent.com/hagezi/dns-blocklists/refs/heads/main/dnsmasq/multi.txt" || { echo "Failed to download multi-normal.txt"; exit 1; }
          curl -fsSL -o pop-ups.txt "https://raw.githubusercontent.com/hagezi/dns-blocklists/refs/heads/main/dnsmasq/popupads.txt" || { echo "Failed to download pop-ups.txt"; exit 1; }
          curl -fsSL -o fake.txt "https://raw.githubusercontent.com/hagezi/dns-blocklists/refs/heads/main/dnsmasq/fake.txt" || { echo "Failed to download fake.txt"; exit 1; }
          curl -fsSL -o ultimate.txt "https://raw.githubusercontent.com/hagezi/dns-blocklists/refs/heads/main/dnsmasq/ultimate.txt" || { echo "Failed to download ultimate.txt"; exit 1; }
          ls -l *.txt  # Show file sizes

      - name: Generate filtered blocklist
        run: |
          python3 -c "
          import re

          subtract_files = ['multi-normal.txt', 'pop-ups.txt', 'fake.txt']

          to_remove_domains = set()
          for filename in subtract_files:
              with open(filename, 'r') as f:
                  for line in f:
                      line = line.strip()
                      if line and not line.startswith('#'):
                          if line.startswith('local=/'):
                              domain = line[7:].rstrip('/').lower()
                          else:
                              domain = line.lower()
                          if domain and re.match(r'^[a-z0-9\.-]+$', domain):
                              to_remove_domains.add(domain)
              print(f'Domains extracted from {filename}: {len(to_remove_domains)} (cumulative)')

          # Read ultimate list and filter
          filtered_lines = []
          with open('ultimate.txt', 'r') as f:
              for line in f:
                  line = line.strip()
                  if line and not line.startswith('#'):
                      if line.startswith('local=/'):
                          domain = line[7:].rstrip('/').lower()
                          if domain and re.match(r'^[a-z0-9\.-]+$', domain) and domain not in to_remove_domains:
                              filtered_lines.append(line)  # Keep original line
                  else:
                      filtered_lines.append(line)  # Keep comments and empty lines

          # Write to output file
          with open('blocklist.txt', 'w') as out:
              for line in filtered_lines:
                  out.write(line + '\n')

          print(f'Generated blocklist with {len(filtered_lines)} lines')
          "

      - name: Commit and push changes
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: 'chore: update blocklist from Hagezi Ultimate minus (Normal, Pop-ups, Fake)'
          file_pattern: blocklist.txt
          commit_user_name: github-actions[bot]
          commit_user_email: 41898282+github-actions[bot]@users.noreply.github.com
